# Generated by Django 2.2.5 on 2019-10-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribovision', '0002_mastertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moleculenames',
            fields=[
                ('moleculename', models.CharField(db_column='MoleculeName', max_length=6, primary_key=True, serialize=False)),
                ('moleculetype', models.CharField(blank=True, db_column='MoleculeType', max_length=70, null=True)),
                ('moleculegroup', models.CharField(blank=True, db_column='MoleculeGroup', max_length=5, null=True)),
            ],
            options={
                'db_table': 'MoleculeNames',
                'managed': False,
            },
        ),
    ]
