# Generated by Django 2.2.5 on 2020-03-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chainlist',
            fields=[
                ('chainlist_id', models.IntegerField(db_column='ChainList_id', primary_key=True, serialize=False)),
                ('chainname', models.CharField(blank=True, db_column='ChainName', max_length=3, null=True)),
            ],
            options={
                'db_table': 'ChainList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Threedstructures',
            fields=[
                ('number_3d_structure_id', models.AutoField(db_column='3D_structure_id', primary_key=True, serialize=False)),
                ('structurename', models.CharField(blank=True, db_column='StructureName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ThreeDStructures',
                'managed': False,
            },
        ),
    ]
