# Generated by Django 2.2.5 on 2020-03-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0003_secondarytertiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolymerAlignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Polymer_Alignments',
                'managed': False,
            },
        ),
    ]
