# Generated by Django 2.2.5 on 2020-04-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0004_polymeralignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrucfoldChains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'StrucFold_Chains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StrucfoldResidues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'StrucFold_Residues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StructuralFolds',
            fields=[
                ('struc_fold_id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(db_column='Level', max_length=45)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('classification_system', models.CharField(max_length=45)),
                ('external_id', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Structural_Folds',
                'managed': False,
            },
        ),
    ]
