# Generated by Django 2.2.13 on 2021-04-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desire_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecoddomains',
            fields=[
                ('uid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ecod_domain_id', models.TextField(blank=True, null=True)),
                ('manual_rep', models.TextField(blank=True, null=True)),
                ('f_id', models.TextField(blank=True, null=True)),
                ('pdb', models.TextField(blank=True, null=True)),
                ('chain', models.TextField(blank=True, null=True)),
                ('pdb_range', models.TextField(blank=True, null=True)),
                ('seqid_range', models.TextField(blank=True, null=True)),
                ('unp_acc', models.TextField(blank=True, null=True)),
                ('arch_name', models.TextField(blank=True, null=True)),
                ('x_name', models.TextField(blank=True, null=True)),
                ('h_name', models.TextField(blank=True, null=True)),
                ('t_name', models.TextField(blank=True, null=True)),
                ('f_name', models.TextField(blank=True, null=True)),
                ('asm_status', models.TextField(blank=True, null=True)),
                ('ligand', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'EcodDomains',
                'managed': False,
            },
        ),
    ]
