# Generated by Django 2.1.3 on 2018-11-21 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdResidues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.IntegerField(db_column='AD_id')),
                ('residuep_id', models.IntegerField(db_column='residueP_id')),
            ],
            options={
                'managed': False,
                'db_table': 'AD_Residues',
            },
        ),
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('aln_id', models.AutoField(db_column='Aln_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('method', models.CharField(db_column='Method', max_length=45)),
                ('source', models.CharField(db_column='Source', max_length=10)),
            ],
            options={
                'managed': False,
                'db_table': 'Alignment',
            },
        ),
        migrations.CreateModel(
            name='AlnData',
            fields=[
                ('alndata_id', models.AutoField(db_column='AlnData_id', primary_key=True, serialize=False)),
                ('aln_pos', models.IntegerField()),
                ('polymer_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Aln_Data',
            },
        ),
        migrations.CreateModel(
            name='AlnDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartment', models.CharField(max_length=1)),
            ],
            options={
                'managed': False,
                'db_table': 'Aln_Domains',
            },
        ),
        migrations.CreateModel(
            name='AssociatedData',
            fields=[
                ('data_id', models.AutoField(db_column='Data_id', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='Type', max_length=45)),
                ('value', models.CharField(db_column='Value', max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'Associated_Data',
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('nom_id', models.AutoField(primary_key=True, serialize=False)),
                ('new_name', models.CharField(max_length=10)),
                ('occurrence', models.CharField(max_length=1)),
                ('moleculegroup', models.CharField(blank=True, db_column='MoleculeGroup', max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Nomenclature',
            },
        ),
        migrations.CreateModel(
            name='OldName',
            fields=[
                ('old_id', models.AutoField(primary_key=True, serialize=False)),
                ('old_name', models.CharField(max_length=45)),
                ('n_b_y_h_a', models.CharField(db_column='N_B_Y_H_A', max_length=3)),
            ],
            options={
                'managed': False,
                'db_table': 'Old_name',
            },
        ),
        migrations.CreateModel(
            name='PolymerData',
            fields=[
                ('pdata_id', models.AutoField(db_column='PData_id', primary_key=True, serialize=False)),
                ('gi', models.CharField(db_column='GI', max_length=45, unique=True)),
                ('genesymbol', models.CharField(blank=True, db_column='GeneSymbol', max_length=45, null=True)),
                ('genedescription', models.CharField(blank=True, db_column='GeneDescription', max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Polymer_Data',
            },
        ),
        migrations.CreateModel(
            name='Residues',
            fields=[
                ('resi_id', models.AutoField(primary_key=True, serialize=False)),
                ('resnum', models.IntegerField(db_column='resNum')),
                ('unmodresname', models.CharField(db_column='unModResName', max_length=1)),
                ('modresname', models.CharField(blank=True, db_column='modResName', max_length=1, null=True)),
                ('altname', models.CharField(blank=True, db_column='altName', max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Residues',
            },
        ),
        migrations.CreateModel(
            name='Secondarystructures',
            fields=[
                ('secstr_id', models.AutoField(db_column='SecStr_id', primary_key=True, serialize=False)),
                ('moleculegroup', models.CharField(db_column='MoleculeGroup', max_length=45)),
                ('variation', models.CharField(db_column='Variation', max_length=45)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('font_size_svg', models.DecimalField(blank=True, db_column='Font_Size_SVG', decimal_places=1, max_digits=2, null=True)),
                ('font_size_canvas', models.DecimalField(blank=True, db_column='Font_Size_Canvas', decimal_places=1, max_digits=2, null=True)),
                ('circle_radius', models.DecimalField(blank=True, db_column='Circle_Radius', decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'SecondaryStructures',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('strain_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('strain', models.CharField(blank=True, max_length=100, null=True)),
                ('taxid', models.IntegerField(blank=True, null=True)),
                ('abbreviation', models.CharField(blank=True, db_column='Abbreviation', max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Species',
            },
        ),
        migrations.CreateModel(
            name='SpeciesTaxgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'Species_TaxGroup',
            },
        ),
        migrations.CreateModel(
            name='SsData',
            fields=[
                ('ssd_id', models.AutoField(db_column='SSD_id', primary_key=True, serialize=False)),
                ('map_index', models.IntegerField()),
                ('x', models.FloatField(blank=True, db_column='X', null=True)),
                ('y', models.FloatField(blank=True, db_column='Y', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'SS_Data',
            },
        ),
        migrations.CreateModel(
            name='Taxgroups',
            fields=[
                ('taxgroup_id', models.IntegerField(primary_key=True, serialize=False)),
                ('grouplevel', models.CharField(blank=True, db_column='groupLevel', max_length=45, null=True)),
                ('groupname', models.CharField(blank=True, db_column='groupName', max_length=45, null=True)),
                ('taxid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'TaxGroups',
            },
        ),
        migrations.CreateModel(
            name='PolymerMetadata',
            fields=[
                ('polymer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='alignments.PolymerData')),
                ('accession_type', models.CharField(max_length=45)),
                ('polymer_type', models.CharField(max_length=45)),
                ('accession', models.CharField(blank=True, max_length=45, null=True)),
                ('fullseq', models.TextField(blank=True, db_column='Fullseq', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Polymer_metadata',
            },
        ),
    ]
