site_name: ProteoVision
nav:
    - Home: index.md
    #- About: About.md
    - Guide:
        #- ProteoVision Summary: ProteoVision_Summary.md
        - Basic Navigation: Basic_Navigation.md
        - Advanced features: Advanced_Features.md
        - Saving: Saving.md
        - ProteoVision Data: ProteoVision_Data.md
        - Import User-supplied Data: Import_User-supplied_Data.md
        - Acknowledgements: Acknowledgements.md
theme: readthedocs